### PR TITLE
create subpage layout, update templates and style - fix #5

### LINKED ISSUE #5: Enhance the header on the subpages
My suggestion is to replace the hero image on the subpages with a smaller top bar containing only the logo e.g. centre aligned logo with a transparent background. 

With this approach we can improve the UX of presenting the people immediately with the context of the selected page :-)

### PR DESCRIPTION
**Pull request by radibit**
Hi @verpixelt I applied the proposed changes regarding the header component on the subpage templates. Can you please verify the solution and advise if I it's ok or if you have some suggestion to improve it? Thanks :smiley:

### CODE REVIEW

**Comment by lukaszklis** [comment]
I can take a look at it later today. :)

**Comment by Kriesse** [comment]
Awesome work @radibit, thank you!
Added a small tweak to align the menu toggle button.
@lukaszklis Can you review and merge if everything looks good?

**Comment by verpixelt** [comment]
Will have a look later today.

**Comment by radibit** [comment]
@Kriesse @verpixelt Thank you for the update!

**Comment by verpixelt** [comment]
Thanks @radibit for your work. I'm not entirely happy with the looks, but it definitely solves the problem of not recognising a page change and the repetition of the big 'ol header image. Let's keep it that way for now. I will open another issue where we can discuss further changes. Thanks again for taking the time and helping to make that site even better :+1:

**Pull request merged**
